spring.application.name=CareerTrack

server.port=8080


# ===============================
# H2 DATABASE
# ===============================

spring.datasource.url=jdbc:h2:file:./data/careertrack
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# H2 WEB CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ===============================
# ERROR RESPONSE
# ===============================

server.error.include-message=always
server.error.include-binding-errors=always
